### ISSUE TITLE
Edit-DESCRIPTION specifications

### ISSUE THREAD

**Issue by dendousi** [jdogresorg/Broadcast-Token-Naming-System#24]
Hi.

ISSUE command
Formats Version 1 - Edit DESCRIPTION
I would like to confirm this.

bt:ISSUE|1|TICK|DESCRIPTION

When I used
Besides DESCRIPTION, MAX_SUPPLY and MAX_MINT were edited to 0.
I thought I would only edit DESCRIPTION, but is this result as per the specifications?

**Comment by jdogresorg** [comment]
yes, if you only want to edit the description, then FORMAT 1 is the simplest way, as it only edits the description field, and does not include any additional fields.

`bt:ISSUE|1|TICK|DESCRIPTION`
