### ISSUE TITLE
XCP asset owner at block height X

### ISSUE THREAD

**Issue by jdogresorg** [jdogresorg/Broadcast-Token-Naming-System#28]
Currently BTNS only looks up the CURRENT owner of an XCP token... not the owner at the time of the transaction.

This is causing issues with BTNS, where ISSUES which were once valid, are now considered invalid, because the asset ownership of the XCP token has been transferred.

update `getAssetInfo()` to take an optional `$block_index`, which will then query the last issuance before `$block_index` to determine asset owner address at time of BTNS tx

**Comment by commswap** [comment]
another case SMAN/BTNS deployed before SMAN/CP asset ,It was a valid Issuance 

9 months ago (2023-05-14T20:02:00Z GMT)

https://xchain.io/tx/2351278

SMAN/Counterparty  Asset Issued 
6 months ago (2023-07-27T12:27:00Z GMT)

https://xchain.io/tx/2446895

**Comment by jdogresorg** [comment]
issue should be fixed now
